### PR TITLE
Update footer.html

### PR DESCRIPTION
**Pull request by inverse**
Format year to ensure republishing is correct

### CODE REVIEW

**Review by ian-bartholomew — APPROVED** [review]
Thanks!

**Review by fpiwowarczyk — APPROVED** [review]
Nice catch ;)

**Comment by inverse** [comment]
Ouch :( looks like it rendered wrong `232323`

I followed this https://gohugo.io/functions/now/

**Comment by inverse** [comment]
Looks like it ready needs to be `2006`

**Comment by inverse** [comment]
Sorry about that - thanks for the quick fix :pray:

**Comment by fpiwowarczyk** [comment]
No worries, I should have test in before merging. Thanks for contribution!

**Pull request merged**
